#!/usr/bin/perl

use File::Basename;
use lib dirname (__FILE__) ;

my $pidi=0;

my $FFPROBE_OEM = '/usr/bin/ffprobe.oem ';

sub createArglist(){
	my $arglist = '';
	foreach my $current (0 .. $#ARGV) {
		if ($ARGV[$current] =~ m%\s% or $ARGV[$current] =~ m%\(% or $ARGV[$current] =~ m%\)% or $ARGV[$current] =~ m%\&%){
	   		$arglist .= ' "' .$ARGV[$current] . '"';
		}else{$arglist .= ' ' .$ARGV[$current];}
	}
	return $arglist;

}

$arglist = createArglist();

#reduce to 1 second analysis
$arglist =~ s%3000000%1000000%;

$pid = open ( LS, '-|', $FFPROBE_OEM . ' ' . $arglist . ' 2>&1');
my $output = do{ local $/; <LS> };
close LS;

my $line= '';
my $skip = 0;

my $index = 0;
my @index;
my $current=0;
my $stdout=0;
while(($line) = $output =~ m%^(.*?)\n%){
	$output =~ s%^.*?\n%%;
	if ($line =~ m%hdmv_pgs_subtitle% and $line =~ m%Stream \#%){
		$skip = 1;
		$index[$index] = 1
	}elsif ($line =~ m%dvd_subtitle% and $line =~ m%Stream \#%){
		$skip = 1;
		$index[$index] = 1
	}elsif($line =~ m%Stream \#%){
		$skip = 0;
	}
	if ($line =~ m%Stream \#%){
		$index++;
	}

	if ($line =~ m%^        \{%){
		if ($index[$current] == 1){
			$skip = 1;
		}
		$current++;
	}elsif ($skip == 1 and $line =~ m%^        \}%){
		$skip = 2;
	}elsif ($line =~ m%^\{%){
		$stdout = 1;
		$skip = 0;
	}


	if ($skip == 0){
		if ($stdout){
			print STDOUT $line . "\n"
		}else{
			print STDERR $line . "\n"
		}
		print LOG $line  . "\n";
	}elsif ($skip == 2){
		$skip =0;
	}else{
		print LOG "SKIP -> " . $line  . "\n";
	}

}

close(LOG);
print $output;